# Site settings
title: "la vie est belle"
author: "Heather :fire: Luna"
description: "la vie est belle - life is beautiful. This blog is a personal exercise in focussing more on the positives and accomplishments in my life rather than the negative and short-comings."
keywords: "Technology, Life, Development, Career, "
biography: "I'm just a girl in the world... (Gwen Stefani) who loves technology and lots of other cool things!" 
inspiration: this blog in Jekyll inspired by <a href="https://twitter.com/webology">Jeff Triplett</a>


baseurl: ""
url: "http://heats.life"

twitter_username: h34th3r329
github_username: daheats
linkedin_username: heather-luna

simple_search: http://google.com/search
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/

gems:
  #- jekyll-archives
  #- jekyll-coffeescript
  #- jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jemoji
